In [0]:
import pandas as pd
import numpy as np
import math

In [0]:
def mean(df, columnNames):
  return np.asarray(np.mean(df[columnNames]))

In [0]:
def std(df, columnNames):
  return np.asarray(np.std(df[columnNames]))

In [0]:
def energy(df, columnNames):
  return np.asarray((df[columnNames]**2).mean())

In [0]:
def rms(df, columnNames):
  return np.asarray((df[columnNames]**2).mean()**0.5)

In [0]:
from scipy.stats import iqr
def IQR(df, columnNames):
  return np.asarray(iqr(df[columnNames], rng=(25,75), interpolation='midpoint', axis = 0))

In [0]:
def min_max(df, columnNames):
  return np.asarray(df[columnNames].min()), np.asarray(df[columnNames].max()) 

In [0]:
from scipy.stats import kurtosis, skew

def Skew(df, columnNames):
  return skew(df[columnNames],axis=0)

def Kurtosis(df, columnNames):
  return kurtosis(df[columnNames],axis=0)

In [9]:
import numpy as np
def correlation(x, y):
    std_x = (x - x.mean()) / x.std(ddof=0)
    std_y = (y - y.mean()) / y.std(ddof=0)
    
    print(type(std_x),std_x.shape,std_x)
    print('....',type(std_y),std_y)
    mm = (std_x * std_y).mean()
    print(type(mm), mm)
    
    return (std_x * std_y).mean()

#x = y =  np.arange(0.0,5.0,1.0)
x =  np.asarray([-1,2,-3,4])
y =   np.asarray([2,-6,1,4])
print(correlation(x, y))

<class 'numpy.ndarray'> (4,) [-0.55708601  0.55708601 -1.29986737  1.29986737]
.... <class 'numpy.ndarray'> [ 0.46460632 -1.65930828  0.19911699  0.99558497]
<class 'numpy.float64'> -0.03697509744106492
-0.03697509744106492


In [0]:
def median(df, columnNames):
  return np.asarray(df[columnNames].median())

In [0]:
def mad(df, columnNames):
  return  np.asarray(df[columnNames].mad(axis = 0)) 

In [0]:
def corr(df, col1, col2):
  return  df[col1].corr(df[col2])

In [13]:
def magnitude(df, columnNames):
  return np.linalg.norm(df[columnNames].values,axis=1)


"\nd = { 'Id': [1, 2, 1,3],\n          'Age':[20, 21, 19, 18]}\n \n# Create DataFrame\nddd = pd.DataFrame(d)\nprint(ddd)\nx = np.asarray([1, 2, 1,3])\ny =  np.asarray([20, 21, 19, 18])\n\nprint(correlation(x, y))\nprint(corr(ddd, 'Id' ,'Age'))\n\n\n\ndata = { 'Id': [1, 2, 1,3],\n          'Age':[20, 21, 19, 18]}\n \n# Create DataFrame\ndf = pd.DataFrame(data)\n\n#df['aa'] = np.asarray((df[['Id','Age']]**2).sum(axis=1))\n\n#b = np.asarray(np.sqrt(np.square(df[['Id','Age']]).sum(axis=1)))\n#print(b, type(b))\n\n# calculate magnitude\ndf['bb'] = np.sqrt(np.square(df[['Id','Age']]).sum(axis=1))\nprint(df)\n\n"

In [0]:

# Creating the dataframe

df = pd.DataFrame({"x":[1.2, -1.2, 5.0, 4.3, -3.7], 
                   "y":[-3.2, 6.2, 5.1, 4.3, -3.7], 
                   "z":[-2.2, -1.2, 9.1, -1.3, 3.7]}) 


In [15]:
df

x    y    z
0  1.2 -3.2 -2.2
1 -1.2  6.2 -1.2
2  5.0  5.1  9.1
3  4.3  4.3 -1.3
4 -3.7 -3.7  3.7

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
x    5 non-null float64
y    5 non-null float64
z    5 non-null float64
dtypes: float64(3)
memory usage: 248.0 bytes


In [17]:
magnitude(df, ['x','y','z'])

array([ 4.06448029,  6.42806347, 11.56805947,  6.21852072,  6.40858799])

In [0]:

# Creating the dataframe

df = pd.DataFrame({"x":[1.2, -1.2, 5.0, 4.3, -3.7], 
                   "y":[-3.2, 6.2, 5.1, 4.3, -3.7], 
                   "z":[-2.2, -1.2, 9.1, -1.3, 3.7],
                   "magnitude":[4.0644803, 6.428063, 11.56806, 6.218521, 6.408588]}) 


In [19]:
df

x    y    z  magnitude
0  1.2 -3.2 -2.2   4.064480
1 -1.2  6.2 -1.2   6.428063
2  5.0  5.1  9.1  11.568060
3  4.3  4.3 -1.3   6.218521
4 -3.7 -3.7  3.7   6.408588

In [20]:
mean(df, ['x','y','z','magnitude'])

array([1.12      , 1.74      , 1.62      , 6.93754246])

In [21]:
std(df, ['x','y','z','magnitude'])

array([3.27987805, 4.28326978, 4.27429526, 2.48002149])

In [22]:
rms(df, ['x','y','z','magnitude'])

array([3.46583323, 4.62320235, 4.57099552, 7.36749632])

In [23]:
min_max(df, ['x','y','z','magnitude'])

(array([-3.7      , -3.7      , -2.2      ,  4.0644803]),
 array([ 5.     ,  6.2    ,  9.1    , 11.56806]))

In [24]:
median(df, ['x','y','z','magnitude'])

array([ 1.2     ,  4.3     , -1.2     ,  6.408588])

In [27]:
corr(df, 'x', 'y')

0.5218454997131404

In [29]:
 corr(df, 'y', 'z')

0.13803831980206582

In [31]:
corr(df, 'x', 'z')

0.22751708105563612

In [45]:
mad(df, ['x','y','z','magnitude'])

array([2.856     , 4.152     , 3.824     , 1.85220702])

In [36]:
from scipy import stats
x = np.array([1.2, -1.2, 5.0, 4.3, -3.7])
stats.median_absolute_deviation(x)

4.59606

In [37]:
y = np.array([-3.2, 6.2, 5.1, 4.3, -3.7])
stats.median_absolute_deviation(y)

2.81694

In [38]:
z = np.array([-2.2, -1.2, 9.1, -1.3, 3.7])
stats.median_absolute_deviation(z)

1.4826000000000001

In [39]:
mag = np.array([4.0644803, 6.428063, 11.56806, 6.218521, 6.408588])
stats.median_absolute_deviation(mag)

0.28179333419999997